### ISSUE TITLE
Learned camera poses

### ISSUE THREAD

**Issue by FantasticOven2** [JiahuiLei/MoSca#7]
Hey author,

Thanks for this amazing work! I saw the reconstruction on dyncheck dataset w/o camera poses is pretty good. 

I am curious about the quality of the learned camera poses. Did you try to visualize the learned camera trajectory and have quantitative results on the learned pose error?

**Comment by FantasticOven2** [comment]
Hey author,

Thanks for this amazing work! I saw the reconstruction on dyncheck dataset w/o camera poses is pretty good. 

I am curious about the quality of the learned camera poses. Did you try to visualize the learned camera trajectory and have quantitative results on the learned pose error?

**Comment by JiahuiLei** [comment]
Thanks for you interest, we have updated a new paper at

https://www.cis.upenn.edu/~leijh/projects/mosca/pub/mosca_v2.pdf

And tested the camera pose in Tab.3, the code is open now, thanks.
